spring:
  application:
    name: demo-app
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop